import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';
import axios from 'axios';

export default function Home() {


    const [quiz, setQuiz] = useState([])

    const getQuizzes = async () => {
        try {
            // GET-request til /api/quiz
            const response = await axios.get('/api/quiz')

            // response.data kommer fra axios
            // success er noe som jeg har laget i responsen
            if (response?.data?.success) {
                // oppdaterer state med data fra API
                setQuiz(response.data.data)
            }
        } catch (error) {
            // console.log av feilen
            console.log(error?.response?.data)
        }
    }

    // trigger henting av data når komponenten lages
    useEffect(() => {
        getQuizzes()
    }, [])

    const allText = JSON.stringify(quiz);

    


    
    return (

        
        <div className={styles.container}>
            <Head>
                <title>Get information</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* ---------------- Title -------------------- */}
            <main className={styles.main}>
                <h1 className={styles.title}>
                    <a href="/">Til Forsiden</a>
                </h1>
                <h3> Her skal man kunne få inn informasjonen </h3>
                {/* ---------- Elementer --------------- */}
                <p>{allText}</p>

            </main>
            {/* ---------------- Footer --------------- */}
            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}
