import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Oppgave 9</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
{/* ---------------- Title -------------------- */}
      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="/">Velkommen til oppgave 9!</a>
        </h1>
{/* ---------- Elementer --------------- */}
        <div className={styles.grid}>

          <a href="get" className={styles.card}>
            <h2>Motta informasjon &rarr;</h2>
            <p>
              Går den inn i post mappen og bruker index.js der
            </p>
          </a>
          <a href="/post" className={styles.card}>
            <h2>Sende informasjon &rarr;</h2>
            <p>
              Går den inn i post mappen og bruker index.js der
            </p>
          </a>
        </div>
      </main>
{/* ---------------- Footer --------------- */}
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
