import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { useState, useEffect } from 'react'
import axios from 'axios';


export default function Home() {


    const [quiz, setQuiz] = useState([])
    const [error, setError] = useState(null)
    const [question, setQuestion] = useState('');
    const [answers, setAnswers] = useState([]);
    const [answere, setAnswere] = useState('');

    // håndtere endringer i input
    const handleQuestionChange = (event) => {
        setQuestion(event.target.value)
    }

    // trigger sending av data til API
    const createQuiz = async () => {
        try {
            // sender POST-request via axios.post
            // sender til /api/quiz
            // sender med data { question }
            const response = await axios.post('/api/quiz', { question,answere })

            if (response?.data?.success) {
                setQuiz(response.data.data)
            }
        } catch (err) {
            // hvis feil oppdatere error staten
            // err?.response?.data? kommer fra axios
            // .error har vi laget selv i API
            setError(err?.response?.data?.error)
        }
    }

    // håndtere sending av skjema
    const handleSubmit = async (event) => {
        console.log(event.value);
        // forhindre default adferd
        event.preventDefault()
        // trigge funksjonen som sender data til API
            await createQuiz()


    }

    // Hvis feil gi beskjed om dette til brukeren
    // Vi skal håndtere denne bedre i fremtidig leksjoner
    if (error) {
        return <p>Noe gikk galt: {error}</p>
    }





    return (
        <div className={styles.container}>
            <Head>
                <title>Sende stuff(POST)</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* ---------------- Title -------------------- */}
            <main className={styles.main}>
                <h1 className={styles.title}>
                    <a href="/">Til Forsiden</a>
                </h1>
                <h3> Her skal man kunne sende informasjonen </h3>
                {/* ---------- Elementer --------------- */}

            <section>
                    <h1>Create Quiz</h1>
                    <form style={{ marginBottom: '2rem' }} onSubmit={handleSubmit}>
                        <label htmlFor="question">Lag nytt spørsmål </label>
                        <input
                            id="question"
                            type="text"
                            name="question"
                            value={question}
                            onChange={handleQuestionChange}
                        />
                        <br />
                        <label htmlFor="question">Answere </label>
                        <input
                            id="question"
                            type="text"
                            name="question"
                            value={answere[0]}
                            onChange={handleQuestionChange}
                        />
                        <br />
                        <label htmlFor="question">Answere </label>
                        <input
                            id="question"
                            type="text"
                            name="quesstion"
                            value={answere[1]}
                            onChange={handleQuestionChange}
                        />
                        <br />
                        <button type="submit">Send</button>
                    </form>
            </section>
                <section>{JSON.stringify(quiz)}</section>

            </main>
            {/* ---------------- Footer --------------- */}
            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}
