import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export default function Home() {



    return (
        <div className={styles.container}>
            <Head>
                <title>Oppgave 9</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* ---------------- Title -------------------- */}
            <main className={styles.main}>
                <h1 className={styles.title}>
                    <a href="/">Til Forsiden</a>
                </h1>
                <h3> Her skal man kunne sende informasjonen </h3>
                {/* ---------- Elementer --------------- */}

            </main>
            {/* ---------------- Footer --------------- */}
            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}
